# Utilized GitHub 'releases' feature to download the latest for linux-x86_64 (ln:19) : 

function get-assets() {
  # ARG[0] should be github <user|org>/<project> eg. 'neovim/neovim'
  latest="https://github.com/${1}/releases/latest"
   
  echo `curl -#L ${latest}     |
    ag -A20 Assets             |
    ag expanded_assets         |
    awk -F'src="' '{print $2}' |
    awk -F'"' '{print $1}'`
}

function select-architecture() {
  # ARG[0] should be the 'expanded_assets' url generated by 'get-assets' above
  url="$1"
  query="linux\-x86_64.tar.gz|linux\-amd64.tar.gz|linux\-x86_64.txz|linux\-amd64.txz"
   
  echo `curl -#L ${url}         |
    ag "${query}"               |
    ag href                     |
    awk -F'href="' '{print $2}' |
    awk -F'"' '{print $1}'`
}

function downstract() {
  # ARG[0] should be the <user|org>/<repo>/releases/download/<version>/<archive> path from 'select-architecture'
  curl -#L "https://github.com/${1}" | tar xzf -
}

function grab-latest() {
  # ARG[0] should be github <user|org>/<project> eg. 'neovim/neovim'
  repo="$1"
  assets=`get-assets ${repo}`
  printf "[1A[0G"
  arch=`select-architecture ${assets}`
  printf "[1A[0G"

  downstract ${arch}
}
