# Utilized GitHub 'releases' feature to download the latest for linux-x86_64 (ln:19) : 

function get-assets() {
  # ARG[0] should be github <user|org>/<project> eg. 'neovim/neovim'
  latest="https://github.com/${1}/releases/latest"
   
  echo `curl -#L ${latest}     |
    grep -A20 Assets           |
    grep expanded_assets       |
    awk -F'src="' '{print $2}' |
    awk -F'"' '{print $1}'`
}

function select-architecture() {
  # ARG[0] should be the 'expanded_assets' url generated by 'get-assets' above
  url="$1"
  query='linux-x86_64.tar.gz"\|linux-amd64.tar.gz"\|linux-x86_64.txz"\|linux-amd64.txz"'
   
  printf `curl -#L ${url}       |
    grep ${query}               |
    grep href                   |
    awk -F'href="' '{print $2}' |
    awk -F'"' '{print $1}'`
}

function downstract() {
  # ARG[0] should be the <user|org>/<repo>/releases/download/<version>/<archive> path from 'select-architecture'
  case "$1" in
    *gz)
      curl -#L "https://github.com/${1}" | tar xzf -
      ;;
    *xz)
      curl -#L "https://github.com/${1}" | tar xJf -
      ;;
  esac
}

function grab-latest() {
  # ARG[0] should be github <user|org>/<project> eg. 'neovim/neovim'
  repo="$1"
  assets=`get-assets ${repo}`
  printf "\033[1A\033[0G\033[0K"
  arch=`select-architecture ${assets}`
  printf "\033[1A\033[0G\033[0K"

  downstract ${arch}
}
