# Utilized GitHub 'releases' feature to download the latest for linux-x86_64 (ln:19) : 

function get-assets() {
  # ARG[0] should be github <user|org>/<project> eg. 'neovim/neovim'
  latest="https://github.com/${1}/releases/latest"
   
  echo `curl -#L ${latest}  |
    ag -A20 Assets             |
    ag expanded_assets         |
    awk -F'src="' '{print $2}' |
    awk -F'"' '{print $1}'`
}

function select-architecture() {
  # ARG[0] should be the 'expanded_assets' url generated by 'get-assets' above
  url="$1"
   
  echo `curl -#L ${url}                           |
    ag 'linux\-x86_64.tar.gz|linux\-amd64.tar.gz' |
    ag href                                       |
    awk -F'href="' '{print $2}'                   |
    awk -F'"' '{print $1}'`
}

function downstract() {
  # ARG[0] should be the <user|org>/<repo>/releases/download/<version>/<archive> path from 'select-architecture'
  curl -#L "https://github.com/${1}" | tar xzf -
}

function grab-latest() {
  # ARG[0] should be github <user|org>/<project> eg. 'neovim/neovim'
  repo="$1"

  downstract $(select-architecture `get-assets ${repo}`)
}
