#!/bin/bash

# Declare logging
log=/tmp/profile_install.log

function spinner() {
  sym=( '|' '/' '-' '\' )
  $@ &>> /tmp/spinner.log &
  pid=$!

  idx=0
  while [ -d /proc/$pid ]
  do
    echo -ne " ${sym[$idx]}" >&3
    sleep 0.3
    idx=$((($idx + 1) % 3 ))
    echo -ne "\033[2D" >&3
  done
}

function rclear() {
  echo -ne "\033[0K$1"
}

function out-percent() {
  lines=`wc $log|awk '{print $1}'`
  echo "scale = 4 ; $lines / 180 * 100"|bc|awk -F'\.' '{print $1}' 2>/dev/null
}

function get-bins() {
  pushd $HOME/.local/bin 
    curl -#L https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-amd64.tar.gz | tar xzf -
    curl -#L https://github.com/BriskBear/psc/releases/download/0.1.0c/psc-0.1.0c-linux-amd64.txz      | tar xJf -
  popd
}

exec 3>&1
trap 'exec 3>&1 4>&2' 0 1 2 3
exec 1>>$log

ARCH=`uname -a|awk '{print $(NF - 1)}'`
DISTRO=`cat /etc/*{release,version} 2>/dev/null|grep '^ID='|sed -e 's/ID=//g'`
XH=$HOME/.local/etc
XP=$HOME/.local/etc/profile.d

# Use sudo to install dependencies unless already root
[[ $UID == 0 ]]        \
  && export sudo=      \
  || export sudo=`which doas 2>/dev/null || which sudo 2>/dev/null`

# Assign the correct package-manager command
case "$DISTRO" in
  arch|archarm)
    export DEPS=( bc eza git gnupg openssh the_silver_searcher )
    export UPDATE="$sudo pacman -Sy"
    export INSTALL="$sudo pacman -S --noconfirm"
    ;;
  debian|ubuntu)
    export DEPS=( bc bzip2 eza git gnupg silversearcher-ag ssh xz-utils )
    export UPDATE="$sudo apt update"
    export INSTALL="$sudo apt install -y"
    ;;
  *)
    echo "$DISTRO not yet supported"
    exit 1
    ;;
esac

spinner $UPDATE
spinner $INSTALL ${DEPS[@]}

# Display Progress # TODO Come back to this...
# while [[ $(out-percent) -lt 100 ]]
# do
#   rclear "`out-percent`%" >&3
#   sleep 0.1
# done & 

# Create the user-directories for installing profile.d
mkdir -vp $HOME/.local/{bin,etc/profile.d,opt}

# Prevent spinner from interrupting git
GIT_TRACE_PACKET=1
GIT_TRACE=1
GIT_CURL_VERBOSE=1

# Download profile.d
spinner get-bins 2>>$log
spinner git clone https://github.com/briskbear/profile.d --depth 1 $XP 2>>$log || exit 1

# Clear trace config
unset GIT_TRACE_PACKET GIT_TRACE GIT_CURL_VERBOSE

# AutoTrust
for profile in `ls $XP/*.sh`
do
  sed -i -e "s/ : $/ : `date -u +%s`/g" "$profile"
done

# Extract appropriate binaries
spinner tar xf $XP/C/${ARCH}.txz -C ~/.local/bin

# backup and copy .profile
mv $HOME/.profile $XP/profile.bak 2>/dev/null
ln -s $XP/profile $HOME/.profile

echo '[[ $- =~ "i" ]] && [[ -f $HOME/.profile ]] && . ~/.profile' > $HOME/.bashrc
echo 'DONE!' | tee -a $log
