#!/bin/bash

# Simple list of dependencies, find the locally-installed distribution
DEPS=( git gnupg openssh )
XP=$HOME/.local/etc/profile.d
DISTRO=`cat /etc/*{release,version} 2>/dev/null|grep '^ID'|sed -e 's/ID=//g'`

# Use sudo to install dependencies unless already root
[[ $UID == 0 ]]           \
  && ( export sudo= )     \
  || ( export sudo='sudo' )

# Assign the correct package-manager command
case "$DISTRO" in
  arch)
    PKGMGR="$sudo pacman -Sy ; $sudo pacman -S --noconfirm"
    ;;
  debian|ubuntu)
    PKGMGR="$sudo apt update ; $sudo apt install -i"
    ;;
  *)
    echo "$DISTRO not yet supported"
    exit 1
    ;;
esac

$PKGMGR "${DEPS[@]}"

# Create the user-directories for installing profile.d
mkdir -vp $HOME/.local/{bin,etc/profile.d}

# Download profile.d
git clone https://github.com/briskbear/profile.d $XP 2>/tmp/profile.d.log || exit 1

# backup and copy .profile
mv $HOME/.profile $XP/profile.bak 2>/dev/null
cp $XP/profile $HOME/.profile
